name: "Trivy scan & Push"
description: "Generate Trivy scans"

inputs:
  acr_registry:
    description: "Server login path for registry"
    required: true
  acr_repo:
    description: "Repository within registry to target"
    required: true
  acr_name:
    description: "Azure container registry name"
    required: true
  app_name:
    description: "Name of application"
    required: true
  subject_img:
    description: "Full path of subject image with tag"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Trivy vulnerability scanning
      run: ./scripts/image-vulnerability-scan.sh
      shell: bash
      env:
        IMAGE: ${{ inputs.subject_img }}
        PROJECT_NAME: ${{ inputs.app_name }}
        REPORT_DIRECTORY: ${{ github.workspace }}

    - name: Push vulnerability scan
      run: ./scripts/oras-attach.sh
      if: ${{ success() }} # all steps before must succeed
      shell: bash
      env:
        ACR_NAME: ${{ inputs.acr_name }}
        IMAGE: ${{ inputs.subject_img }}
        ARTIFACT: ${{ inputs.app_name }}.sarif
        MEDIA_TYPE: application/sarif+json
